name: Build and push Docker image

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username : ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD  }}
        repository: ilcm96/high-school-project-backend/high-school-project-backend
        registry: docker.pkg.github.com
        tags: latest
